### PR TITLE
Reordering some things

### PR DESCRIPTION
**Pull request by kah3f**

### CODE REVIEW

**Comment by ktm5j** [comment]
Is there a way that you all can take me off this? I've been unable to
figure out how to stop getting these emails from what I can see in GitHub.
Thanks so much.

-Kate

**Comment by kah3f** [comment]
I have no idea where this email is going but I hope it gets somewhere.  You would presumably be getting all the github notifications, not just the learning site.  I am not an admin of the repos so don’t think I can add or remove anybody.  Unless you are “giffordpinchot” I’m not sure how you’re even still in the group.  What is your github ID?

Katherine Holcomb
UVA Research Computing  https://www.rc.virginia.edu

***@***.******@***.***>    434-982-5948

**Comment by ktm5j** [comment]
It's ktm5j. I don't understand it either. Any help would be appreciated,
I'd rather not just set up a rule to trash these. I don't see RC under my
organizations in GitHub, so I don't get why I'm still seeing these.

Thanks
-Kate

**Comment by kah3f** [comment]
I think Neal was the admin and he’s left, but I believe Alex has administrator privileges so I’ll ask.

Katherine Holcomb
UVA Research Computing  https://www.rc.virginia.edu
***@***.******@***.***>    434-982-5948

**Comment by kah3f** [comment]
We can’t find you as a member.  Are you still watching any repos  https://github.com/watching

Also there seems to be an unsubscribe link at the bottom of the email, does that work?

The email says you are receiving them because you modified the open/close state and suggests unsubscribing, from what I can tell (I do not know what “modifying the open/close state” means).

**Comment by ktm5j** [comment]
I apologize, I never got past deleting these emails. I was the victim of a
violent crime and suffered a massive concussion that I've finally recovered
from and just wanted to stop seeing these. Will try the unsubscribe link.

**Comment by kah3f** [comment]
I’m so sorry to hear that.  I hope you are continuing to get better and if you have PTSD can get therapy for that.

**Comment by ktm5j** [comment]
Thank you, I'm doing the best I can. Really appreciate it.

**Pull request merged**
